version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: teste123
      MYSQL_DATABASE: desafio
    volumes:
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/0_init.sql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    container_name: app
    build:
      context: node
    networks:
      - app_network
    depends_on:
      db:
        condition: service_healthy

  proxy:
    image: nginx:1.25.2-alpine
    ports:
      - 80:80
    networks:
      - app_network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/index.html:/www/data/index.html
    depends_on:
      - app
    

  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080
    networks:
      - app_network

networks:
  app_network:
    driver: bridge